import { useMemo, useState } from 'react';
import {
  Box,
  Button,
  Chip,
  InputAdornment,
  Menu,
  MenuItem,
  Select,
  TextField,
  Typography,
} from '@mui/material';
import DownloadIcon from '@mui/icons-material/Download';
import VisibilityIcon from '@mui/icons-material/Visibility';
import SearchIcon from '@mui/icons-material/Search';
import DescriptionIcon from '@mui/icons-material/Description';
import TableChartIcon from '@mui/icons-material/TableChart';
import CodeIcon from '@mui/icons-material/Code';
import ImageIcon from '@mui/icons-material/Image';
import InventoryIcon from '@mui/icons-material/Inventory';
import { GlassCard } from '../components/common/GlassCard';
import { ModuleHeader } from '../components/common/ModuleHeader';
import { KpiCard } from '../components/common/KpiCard';
import { ArtifactViewerPanel } from '../components/workflow/ArtifactViewerPanel';
import { useArtifactsRegistry } from '../context/ArtifactsContext';
import type { ApprovalStatus, Artifact, ArtifactFileType } from '../types/artifacts';
import { colors } from '../theme/colors';
import { downloadArtifactAs, FORMAT_LABEL, type ExportFormat } from '../services/artifactExportService';

const STATUS_COLORS: Record<ApprovalStatus, string> = {
  Approved: colors.success,
  'Pending Review': colors.warning,
  Draft: colors.info,
  Rejected: colors.critical,
};

const FILE_ICON: Record<ArtifactFileType, typeof DescriptionIcon> = {
  docx: DescriptionIcon,
  xlsx: TableChartIcon,
  yaml: CodeIcon,
  png: ImageIcon,
};

const EXPORT_FORMATS: ExportFormat[] = ['docx', 'pdf', 'xlsx', 'pptx', 'txt'];

function downloadCatalogCsv(artifacts: Artifact[]): void {
  const header = ['Name', 'Source', 'Generated By', 'Model', 'Version', 'Status', 'Risk', 'Generated'];
  const rows = artifacts.map((a) =>
    [
      a.name,
      a.sourceLabel ?? a.sourceHub ?? '',
      a.generatedBy,
      a.modelUsed,
      `v${a.version}`,
      a.approvalStatus,
      a.riskRating ?? '',
      a.timestamp ?? a.generatedDate,
    ]
      .map((field) => `"${String(field).replace(/"/g, '""')}"`)
      .join(','),
  );
  const csv = [header.join(','), ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'ADIP_Artifact_Catalog.csv';
  a.click();
  URL.revokeObjectURL(url);
}

export function UniversalArtifactsRepository() {
  const { artifacts, clear } = useArtifactsRegistry();
  const [selected, setSelected] = useState<Artifact | null>(null);
  const [query, setQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | ApprovalStatus>('all');
  const [sourceFilter, setSourceFilter] = useState<string>('all');
  const [typeFilter, setTypeFilter] = useState<'all' | ArtifactFileType>('all');
  const [downloadAnchor, setDownloadAnchor] = useState<{ el: HTMLElement; artifact: Artifact } | null>(null);

  const handleExport = async (artifact: Artifact, format: ExportFormat) => {
    setDownloadAnchor(null);
    try {
      await downloadArtifactAs(artifact, format);
    } catch (e) {
      console.error('Artifact export failed', e);
    }
  };

  const sources = useMemo(() => {
    const set = new Set<string>();
    artifacts.forEach((a) => {
      if (a.sourceLabel) set.add(a.sourceLabel);
      else if (a.sourceHub) set.add(a.sourceHub);
    });
    return Array.from(set).sort();
  }, [artifacts]);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return artifacts.filter((a) => {
      if (statusFilter !== 'all' && a.approvalStatus !== statusFilter) return false;
      if (typeFilter !== 'all' && a.fileType !== typeFilter) return false;
      if (sourceFilter !== 'all') {
        const label = a.sourceLabel ?? a.sourceHub ?? '';
        if (label !== sourceFilter) return false;
      }
      if (!q) return true;
      const haystack = [a.name, a.generatedBy, a.modelUsed, a.sourceLabel, a.executiveSummary]
        .filter(Boolean)
        .join(' ')
        .toLowerCase();
      return haystack.includes(q);
    });
  }, [artifacts, query, statusFilter, sourceFilter, typeFilter]);

  const stats = useMemo(() => {
    const totals = { total: artifacts.length, approved: 0, pending: 0, sources: sources.length };
    artifacts.forEach((a) => {
      if (a.approvalStatus === 'Approved') totals.approved += 1;
      else if (a.approvalStatus === 'Pending Review') totals.pending += 1;
    });
    return totals;
  }, [artifacts, sources.length]);

  return (
    <Box>
      <GlassCard sx={{ p: 1.5, mb: 1.5, display: 'flex', alignItems: 'center', gap: 1 }} hover={false}>
        <InventoryIcon sx={{ color: colors.primary, fontSize: 22 }} />
        <Box sx={{ flex: 1 }}>
          <Box sx={{ fontSize: '0.85rem', fontWeight: 700 }}>Universal Artifacts Repository</Box>
          <Box sx={{ fontSize: '0.65rem', color: colors.text.secondary }}>
            Single source of truth for every AI-generated executive deliverable across ADIP — Requirements, Architecture, Development, Testing, Release, Audit, Governance, Portfolio, Risk, Operations &amp; more
          </Box>
        </Box>
        <Button
          variant="outlined"
          size="small"
          startIcon={<DownloadIcon sx={{ fontSize: 16 }} />}
          onClick={() => downloadCatalogCsv(filtered)}
          sx={{ textTransform: 'none', fontSize: '0.72rem' }}
        >
          Export Catalog (CSV)
        </Button>
        <Button
          size="small"
          onClick={clear}
          sx={{ textTransform: 'none', fontSize: '0.72rem', color: colors.text.muted }}
        >
          Clear
        </Button>
      </GlassCard>

      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr 1fr', md: 'repeat(4, 1fr)' }, gap: 1.5, mb: 1.5 }}>
        <KpiCard label="Artifacts" value={stats.total} suffix="" compact />
        <KpiCard label="Approved" value={stats.approved} suffix="" compact />
        <KpiCard label="Pending Review" value={stats.pending} suffix="" compact />
        <KpiCard label="Source Hubs" value={stats.sources} suffix="" compact />
      </Box>

      <GlassCard sx={{ p: 1.5, mb: 1.5 }}>
        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1, alignItems: 'center' }}>
          <TextField
            size="small"
            placeholder="Search artifacts, generator, model, summary…"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            sx={{ minWidth: 260, flex: 1 }}
            slotProps={{
              input: {
                startAdornment: (
                  <InputAdornment position="start">
                    <SearchIcon sx={{ fontSize: 18, color: colors.text.muted }} />
                  </InputAdornment>
                ),
                sx: { fontSize: '0.78rem' },
              },
            }}
          />
          <Select
            size="small"
            value={sourceFilter}
            onChange={(e) => setSourceFilter(e.target.value as string)}
            sx={{ minWidth: 200, fontSize: '0.78rem' }}
          >
            <MenuItem value="all" sx={{ fontSize: '0.78rem' }}>All sources</MenuItem>
            {sources.map((s) => (
              <MenuItem key={s} value={s} sx={{ fontSize: '0.78rem' }}>{s}</MenuItem>
            ))}
          </Select>
          <Select
            size="small"
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value as 'all' | ApprovalStatus)}
            sx={{ minWidth: 150, fontSize: '0.78rem' }}
          >
            <MenuItem value="all" sx={{ fontSize: '0.78rem' }}>All statuses</MenuItem>
            <MenuItem value="Approved" sx={{ fontSize: '0.78rem' }}>Approved</MenuItem>
            <MenuItem value="Pending Review" sx={{ fontSize: '0.78rem' }}>Pending Review</MenuItem>
            <MenuItem value="Draft" sx={{ fontSize: '0.78rem' }}>Draft</MenuItem>
            <MenuItem value="Rejected" sx={{ fontSize: '0.78rem' }}>Rejected</MenuItem>
          </Select>
          <Select
            size="small"
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value as 'all' | ArtifactFileType)}
            sx={{ minWidth: 130, fontSize: '0.78rem' }}
          >
            <MenuItem value="all" sx={{ fontSize: '0.78rem' }}>All formats</MenuItem>
            <MenuItem value="docx" sx={{ fontSize: '0.78rem' }}>DOCX</MenuItem>
            <MenuItem value="xlsx" sx={{ fontSize: '0.78rem' }}>XLSX</MenuItem>
            <MenuItem value="yaml" sx={{ fontSize: '0.78rem' }}>YAML</MenuItem>
            <MenuItem value="png" sx={{ fontSize: '0.78rem' }}>PNG</MenuItem>
          </Select>
        </Box>
      </GlassCard>

      <GlassCard sx={{ p: 2 }}>
        <ModuleHeader title="Artifact Catalog" subtitle={`${filtered.length} of ${artifacts.length} artifacts shown`} />

        {artifacts.length === 0 ? (
          <Typography variant="caption" color="text.secondary" sx={{ display: 'block', py: 4, textAlign: 'center' }}>
            No artifacts generated yet. Visit any AI Reports tab or AI SDLC Copilot tab and click a Generate action.
          </Typography>
        ) : filtered.length === 0 ? (
          <Typography variant="caption" color="text.secondary" sx={{ display: 'block', py: 4, textAlign: 'center' }}>
            No artifacts match the current filters.
          </Typography>
        ) : (
          <>
            <Box
              sx={{
                display: { xs: 'none', md: 'flex' },
                gap: 2,
                py: 0.5,
                borderBottom: `1px solid ${colors.border.subtle}`,
                mb: 0.5,
              }}
            >
              {[
                { label: 'Artifact', minWidth: 240, flex: true },
                { label: 'Source', minWidth: 160 },
                { label: 'Generated By', minWidth: 130 },
                { label: 'Format', minWidth: 60 },
                { label: 'Version', minWidth: 50 },
                { label: 'Status', minWidth: 110 },
                { label: 'Generated', minWidth: 160 },
                { label: '', minWidth: 200 },
              ].map((c) => (
                <Typography
                  key={c.label || 'actions'}
                  variant="caption"
                  color="text.secondary"
                  sx={{
                    fontWeight: 700,
                    fontSize: '0.62rem',
                    textTransform: 'uppercase',
                    letterSpacing: '0.04em',
                    minWidth: c.minWidth,
                    flex: c.flex ? 1 : undefined,
                    ml: c.label === '' ? 'auto' : undefined,
                  }}
                >
                  {c.label}
                </Typography>
              ))}
            </Box>

            {filtered.map((a) => {
              const FileIcon = FILE_ICON[a.fileType];
              const statusColor = STATUS_COLORS[a.approvalStatus];
              return (
                <Box
                  key={a.id}
                  sx={{
                    display: 'flex',
                    flexWrap: 'wrap',
                    alignItems: 'center',
                    gap: 2,
                    py: 1,
                    borderBottom: `1px solid ${colors.border.subtle}`,
                  }}
                >
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75, minWidth: 240, flex: 1 }}>
                    <FileIcon sx={{ fontSize: 16, color: colors.primary }} />
                    <Box>
                      <Typography variant="caption" sx={{ fontWeight: 700, display: 'block' }}>{a.name}</Typography>
                      {a.executiveSummary && (
                        <Typography
                          variant="caption"
                          color="text.secondary"
                          sx={{ fontSize: '0.62rem', display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: 360 }}
                        >
                          {a.executiveSummary}
                        </Typography>
                      )}
                    </Box>
                  </Box>
                  <Chip
                    label={a.sourceLabel ?? a.sourceHub ?? '—'}
                    size="small"
                    sx={{ height: 20, minWidth: 160, fontSize: '0.65rem', bgcolor: `${colors.secondary}1f`, color: colors.secondary }}
                  />
                  <Typography variant="caption" color="text.secondary" sx={{ minWidth: 130 }}>{a.generatedBy}</Typography>
                  <Typography variant="caption" sx={{ minWidth: 60, fontWeight: 700, textTransform: 'uppercase', fontSize: '0.65rem' }}>{a.fileType}</Typography>
                  <Typography variant="caption" color="text.secondary" sx={{ minWidth: 50 }}>v{a.version}</Typography>
                  <Chip
                    label={a.approvalStatus}
                    size="small"
                    sx={{
                      height: 20,
                      minWidth: 110,
                      fontSize: '0.65rem',
                      fontWeight: 700,
                      bgcolor: `${statusColor}22`,
                      color: statusColor,
                      border: `1px solid ${statusColor}44`,
                    }}
                  />
                  <Typography variant="caption" color="text.secondary" sx={{ minWidth: 160, fontSize: '0.62rem' }}>
                    {a.timestamp ?? a.generatedDate}
                  </Typography>
                  <Box sx={{ ml: 'auto', display: 'flex', gap: 0.5 }}>
                    <Button
                      size="small"
                      startIcon={<VisibilityIcon sx={{ fontSize: 14 }} />}
                      onClick={() => setSelected(a)}
                      sx={{ fontSize: '0.7rem', textTransform: 'none' }}
                    >
                      View
                    </Button>
                    <Button
                      size="small"
                      startIcon={<DownloadIcon sx={{ fontSize: 14 }} />}
                      onClick={(e) => setDownloadAnchor({ el: e.currentTarget, artifact: a })}
                      sx={{ fontSize: '0.7rem', textTransform: 'none' }}
                    >
                      Download
                    </Button>
                  </Box>
                </Box>
              );
            })}
          </>
        )}
      </GlassCard>

      <Menu
        anchorEl={downloadAnchor?.el ?? null}
        open={Boolean(downloadAnchor)}
        onClose={() => setDownloadAnchor(null)}
      >
        {EXPORT_FORMATS.map((f) => (
          <MenuItem
            key={f}
            disabled={!downloadAnchor}
            onClick={() => downloadAnchor && handleExport(downloadAnchor.artifact, f)}
            sx={{ fontSize: '0.78rem' }}
          >
            {FORMAT_LABEL[f]}
          </MenuItem>
        ))}
      </Menu>

      <ArtifactViewerPanel artifact={selected} open={selected !== null} onClose={() => setSelected(null)} />
    </Box>
  );
}
