import { useState } from 'react';
import { Box, Button, Chip, Typography } from '@mui/material';
import VisibilityIcon from '@mui/icons-material/Visibility';
import DescriptionIcon from '@mui/icons-material/Description';
import TableChartIcon from '@mui/icons-material/TableChart';
import CodeIcon from '@mui/icons-material/Code';
import ImageIcon from '@mui/icons-material/Image';
import { GlassCard } from '../common/GlassCard';
import { ModuleHeader } from '../common/ModuleHeader';
import { ArtifactViewerPanel } from './ArtifactViewerPanel';
import type { ApprovalStatus, Artifact, ArtifactFileType } from '../../types/artifacts';
import { colors } from '../../theme/colors';

const statusColors: Record<ApprovalStatus, string> = {
  Approved: colors.success,
  'Pending Review': colors.warning,
  Draft: colors.info,
  Rejected: colors.critical,
};

const fileIcons: Record<ArtifactFileType, typeof DescriptionIcon> = {
  docx: DescriptionIcon,
  xlsx: TableChartIcon,
  yaml: CodeIcon,
  png: ImageIcon,
};

function ArtifactRow({
  artifact,
  onView,
}: {
  artifact: Artifact;
  onView: () => void;
}) {
  const statusColor = statusColors[artifact.approvalStatus];
  const FileIcon = fileIcons[artifact.fileType];

  return (
    <Box
      sx={{
        display: 'flex',
        alignItems: 'center',
        gap: 2,
        py: 1,
        borderBottom: `1px solid ${colors.border.subtle}`,
        flexWrap: 'wrap',
      }}
    >
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75, minWidth: 180 }}>
        <FileIcon sx={{ fontSize: 16, color: colors.primary }} />
        <Typography variant="caption" sx={{ fontWeight: 700 }}>{artifact.name}</Typography>
      </Box>
      <Typography variant="caption" color="text.secondary" sx={{ minWidth: 100 }}>{artifact.generatedBy}</Typography>
      <Typography variant="caption" color="text.secondary" sx={{ minWidth: 60 }}>{artifact.modelUsed}</Typography>
      <Typography variant="caption" color="text.secondary" sx={{ minWidth: 40 }}>v{artifact.version}</Typography>
      <Typography variant="caption" color="text.secondary" sx={{ minWidth: 80 }}>{artifact.generatedDate}</Typography>
      <Chip
        label={artifact.approvalStatus}
        size="small"
        sx={{
          height: 20,
          fontSize: '0.65rem',
          fontWeight: 700,
          bgcolor: `${statusColor}22`,
          color: statusColor,
          border: `1px solid ${statusColor}44`,
        }}
      />
      <Button
        size="small"
        startIcon={<VisibilityIcon sx={{ fontSize: 14 }} />}
        onClick={onView}
        sx={{ ml: 'auto', fontSize: '0.7rem', minWidth: 100 }}
      >
        View Artifact
      </Button>
    </Box>
  );
}

interface ArtifactRepositoryPanelProps {
  artifacts: Artifact[];
  title?: string;
  subtitle?: string;
  emptyMessage?: string;
}

export function ArtifactRepositoryPanel({
  artifacts,
  title = 'Generated Artifacts',
  subtitle = 'AI-generated deliverables',
  emptyMessage = 'No artifacts generated yet. Click Generate to create AI deliverables.',
}: ArtifactRepositoryPanelProps) {
  const [selected, setSelected] = useState<Artifact | null>(null);

  return (
    <>
      <GlassCard sx={{ p: 2, mt: 1.5 }}>
        <ModuleHeader title={title} subtitle={subtitle} />
        {artifacts.length === 0 ? (
          <Typography variant="caption" color="text.secondary" sx={{ display: 'block', py: 2, textAlign: 'center' }}>
            {emptyMessage}
          </Typography>
        ) : (
          <>
            <Box
              sx={{
                display: { xs: 'none', md: 'flex' },
                gap: 2,
                py: 0.5,
                borderBottom: `1px solid ${colors.border.subtle}`,
                mb: 0.5,
              }}
            >
              {['Artifact', 'Generated By', 'Model', 'Version', 'Date', 'Status', ''].map((col) => (
                <Typography
                  key={col || 'action'}
                  variant="caption"
                  color="text.secondary"
                  sx={{
                    fontWeight: 700,
                    fontSize: '0.65rem',
                    textTransform: 'uppercase',
                    letterSpacing: '0.04em',
                    minWidth: col === 'Artifact' ? 180 : col === '' ? 100 : col === 'Model' ? 60 : col === 'Version' ? 40 : col === 'Status' ? 72 : 80,
                    ml: col === '' ? 'auto' : undefined,
                  }}
                >
                  {col}
                </Typography>
              ))}
            </Box>
            {artifacts.map((artifact) => (
              <ArtifactRow key={artifact.id} artifact={artifact} onView={() => setSelected(artifact)} />
            ))}
          </>
        )}
      </GlassCard>

      <ArtifactViewerPanel
        artifact={selected}
        open={selected !== null}
        onClose={() => setSelected(null)}
      />
    </>
  );
}
