/**
 * Universal Artifact Export Service
 * ----------------------------------------------------------------
 * Single, reusable, framework-grade exporter that materializes any
 * {@link Artifact} as a real, opens-in-Office downloadable file in
 * **DOCX**, **XLSX**, **PPTX**, **PDF** or **TXT** format.
 *
 * The service is deliberately self-contained:
 *   - DOCX / XLSX / PPTX are built as Office Open XML (OOXML) packages
 *     using JSZip — no external Office libraries required at runtime.
 *   - PDF is built using jsPDF.
 *   - TXT falls back to a plaintext blob.
 *
 * Every consumer (Universal Artifacts Repository, ArtifactViewerPanel,
 * KPI Catalog generator, Copilot card download button) goes through
 * this single service. Adding a new format means changing one file.
 */

import JSZip from 'jszip';
import jsPDF from 'jspdf';
import type { Artifact, ArtifactSection } from '../types/artifacts';

export type ExportFormat = 'docx' | 'pdf' | 'xlsx' | 'pptx' | 'txt';

interface BuildBlobInput {
  artifact: Artifact;
  format: ExportFormat;
}

/* ------------------------------------------------------------------ */
/* Public API                                                          */
/* ------------------------------------------------------------------ */

export async function downloadArtifactAs(
  artifact: Artifact,
  format: ExportFormat,
): Promise<void> {
  const { blob, filename } = await buildBlob({ artifact, format });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export async function buildBlob({ artifact, format }: BuildBlobInput): Promise<{ blob: Blob; filename: string }> {
  const baseName = stripExtension(artifact.name).replace(/\s+/g, '_');
  switch (format) {
    case 'docx':
      return { blob: await buildDocx(artifact), filename: `${baseName}.docx` };
    case 'xlsx':
      return { blob: await buildXlsx(artifact), filename: `${baseName}.xlsx` };
    case 'pptx':
      return { blob: await buildPptx(artifact), filename: `${baseName}.pptx` };
    case 'pdf':
      return { blob: buildPdf(artifact), filename: `${baseName}.pdf` };
    case 'txt':
    default:
      return { blob: buildTxt(artifact), filename: `${baseName}.txt` };
  }
}

/** Static MIME map exposed for callers that need it (dialog labels). */
export const FORMAT_LABEL: Record<ExportFormat, string> = {
  docx: 'Word (DOCX)',
  pdf: 'PDF',
  xlsx: 'Excel (XLSX)',
  pptx: 'PowerPoint (PPTX)',
  txt: 'Plain text',
};

/** Format used when a user simply clicks "Download" on a card. */
export function defaultFormatFor(artifact: Artifact): ExportFormat {
  switch (artifact.fileType) {
    case 'xlsx':
      return 'xlsx';
    case 'docx':
      return 'docx';
    case 'png':
    case 'yaml':
      return 'txt';
    default:
      return 'docx';
  }
}

/* ------------------------------------------------------------------ */
/* Section helpers                                                     */
/* ------------------------------------------------------------------ */

function ensureSections(artifact: Artifact): ArtifactSection[] {
  if (artifact.sections && artifact.sections.length > 0) return artifact.sections;
  return [
    {
      title: 'Executive Summary',
      content:
        artifact.executiveSummary ??
        `AI-generated artifact: ${artifact.name}.`,
    },
    {
      title: 'Full Content',
      content: artifact.previewContent,
    },
  ];
}

function buildHeaderRows(artifact: Artifact): string[][] {
  return [
    ['Artifact', artifact.name],
    ['Generated By', artifact.generatedBy],
    ['Model', artifact.modelUsed],
    ['Version', `v${artifact.version}`],
    ['Status', artifact.approvalStatus],
    ['Risk Rating', artifact.riskRating ?? 'Medium'],
    ['Generated', artifact.timestamp ?? artifact.generatedDate],
    ['Source Hub', artifact.sourceLabel ?? artifact.sourceHub ?? '—'],
  ];
}

/* ------------------------------------------------------------------ */
/* TXT                                                                 */
/* ------------------------------------------------------------------ */

function buildTxt(artifact: Artifact): Blob {
  const lines: string[] = [];
  lines.push(artifact.name);
  lines.push('═'.repeat(Math.max(20, artifact.name.length)));
  lines.push('');
  buildHeaderRows(artifact).forEach(([k, v]) => lines.push(`${k.padEnd(14)}: ${v}`));
  lines.push('');
  if (artifact.executiveSummary) {
    lines.push('EXECUTIVE SUMMARY');
    lines.push('─'.repeat(50));
    lines.push(artifact.executiveSummary);
    lines.push('');
  }
  ensureSections(artifact).forEach((section) => {
    lines.push(section.title.toUpperCase());
    lines.push('─'.repeat(Math.max(20, section.title.length)));
    lines.push(section.content);
    lines.push('');
  });
  return new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
}

/* ------------------------------------------------------------------ */
/* PDF (jsPDF)                                                         */
/* ------------------------------------------------------------------ */

function buildPdf(artifact: Artifact): Blob {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 48;
  const lineHeight = 14;
  let y = margin;
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;

  const ensureSpace = (extra: number) => {
    if (y + extra > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const writeLine = (text: string, opts?: { size?: number; bold?: boolean }) => {
    const size = opts?.size ?? 11;
    doc.setFontSize(size);
    doc.setFont('helvetica', opts?.bold ? 'bold' : 'normal');
    const wrapped = doc.splitTextToSize(text, contentWidth);
    wrapped.forEach((wl: string) => {
      ensureSpace(lineHeight);
      doc.text(wl, margin, y);
      y += lineHeight;
    });
  };

  writeLine(artifact.name, { size: 18, bold: true });
  y += 6;

  doc.setDrawColor(180);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  buildHeaderRows(artifact).forEach(([k, v]) => writeLine(`${k}: ${v}`, { size: 9 }));
  y += 10;

  if (artifact.executiveSummary) {
    writeLine('Executive Summary', { size: 13, bold: true });
    writeLine(artifact.executiveSummary, { size: 11 });
    y += 8;
  }

  ensureSections(artifact).forEach((section) => {
    writeLine(section.title, { size: 13, bold: true });
    writeLine(section.content, { size: 10 });
    y += 8;
  });

  return doc.output('blob');
}

/* ------------------------------------------------------------------ */
/* DOCX (Office Open XML)                                              */
/* ------------------------------------------------------------------ */

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function docxParagraph(text: string, opts?: { bold?: boolean; size?: number; heading?: 1 | 2 }): string {
  const sz = opts?.size ?? 22; // half-points (11pt)
  const styleXml = opts?.heading === 1
    ? `<w:pPr><w:pStyle w:val="Heading1"/></w:pPr>`
    : opts?.heading === 2
      ? `<w:pPr><w:pStyle w:val="Heading2"/></w:pPr>`
      : '';
  const runXml = text
    .split('\n')
    .map((line, idx, arr) => {
      const escaped = xmlEscape(line);
      const breakXml = idx < arr.length - 1 ? '<w:br/>' : '';
      return `<w:r><w:rPr>${opts?.bold ? '<w:b/>' : ''}<w:sz w:val="${sz}"/></w:rPr><w:t xml:space="preserve">${escaped}</w:t>${breakXml}</w:r>`;
    })
    .join('');
  return `<w:p>${styleXml}${runXml}</w:p>`;
}

function buildDocxBody(artifact: Artifact): string {
  const parts: string[] = [];
  parts.push(docxParagraph(artifact.name, { heading: 1, bold: true, size: 36 }));
  buildHeaderRows(artifact).forEach(([k, v]) => parts.push(docxParagraph(`${k}: ${v}`, { size: 18 })));
  if (artifact.executiveSummary) {
    parts.push(docxParagraph('Executive Summary', { heading: 2, bold: true, size: 26 }));
    parts.push(docxParagraph(artifact.executiveSummary));
  }
  ensureSections(artifact).forEach((section) => {
    parts.push(docxParagraph(section.title, { heading: 2, bold: true, size: 26 }));
    parts.push(docxParagraph(section.content));
  });
  return parts.join('');
}

async function buildDocx(artifact: Artifact): Promise<Blob> {
  const zip = new JSZip();
  const body = buildDocxBody(artifact);

  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    ${body}
    <w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/></w:sectPr>
  </w:body>
</w:document>`;

  const stylesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:pPr><w:spacing w:before="240" w:after="120"/></w:pPr><w:rPr><w:b/><w:sz w:val="36"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:pPr><w:spacing w:before="200" w:after="80"/></w:pPr><w:rPr><w:b/><w:sz w:val="26"/></w:rPr></w:style>
</w:styles>`;

  zip.file('[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>`);

  zip.file('_rels/.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`);

  zip.file('word/_rels/document.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>`);

  zip.file('word/document.xml', documentXml);
  zip.file('word/styles.xml', stylesXml);

  return zip.generateAsync({
    type: 'blob',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  });
}

/* ------------------------------------------------------------------ */
/* XLSX (Office Open XML SpreadsheetML)                                */
/* ------------------------------------------------------------------ */

function xlsxColumnLetter(col: number): string {
  let n = col + 1;
  let s = '';
  while (n > 0) {
    const rem = (n - 1) % 26;
    s = String.fromCharCode(65 + rem) + s;
    n = Math.floor((n - 1) / 26);
  }
  return s;
}

function xlsxCell(col: number, row: number, value: string, sharedStringIndex: number, isShared = true): string {
  const ref = `${xlsxColumnLetter(col)}${row + 1}`;
  if (isShared) {
    return `<c r="${ref}" t="s"><v>${sharedStringIndex}</v></c>`;
  }
  return `<c r="${ref}" t="inlineStr"><is><t>${xlsxEscape(value)}</t></is></c>`;
}

function xlsxEscape(s: string): string {
  return xmlEscape(s);
}

interface SheetSpec {
  name: string;
  rows: string[][];
}

function buildSheetsForArtifact(artifact: Artifact): SheetSpec[] {
  // Sheet 1 — Metadata
  const metadata: string[][] = [
    ['Artifact', 'Value'],
    ...buildHeaderRows(artifact),
  ];

  // Sheet 2 — Sections
  const sections: string[][] = [['Section', 'Content']];
  if (artifact.executiveSummary) {
    sections.push(['Executive Summary', artifact.executiveSummary]);
  }
  ensureSections(artifact).forEach((s) => sections.push([s.title, s.content]));

  // Sheet 3 — Generation history
  const history: string[][] = [
    ['Version', 'Date', 'Generated By', 'Model', 'Change Summary'],
    ...artifact.generationHistory.map((h) => [
      `v${h.version}`,
      h.generatedDate,
      h.generatedBy,
      h.modelUsed,
      h.changeSummary,
    ]),
  ];

  return [
    { name: 'Metadata', rows: metadata },
    { name: 'Sections', rows: sections },
    { name: 'History', rows: history },
  ];
}

async function buildXlsx(artifact: Artifact): Promise<Blob> {
  const zip = new JSZip();
  const sheets = buildSheetsForArtifact(artifact);

  // Build a shared strings table — merges every cell value across every sheet.
  const stringIndex = new Map<string, number>();
  sheets.forEach((sheet) =>
    sheet.rows.forEach((row) =>
      row.forEach((cell) => {
        if (!stringIndex.has(cell)) stringIndex.set(cell, stringIndex.size);
      }),
    ),
  );

  const sharedStringsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="${stringIndex.size}" uniqueCount="${stringIndex.size}">
${Array.from(stringIndex.keys()).map((s) => `<si><t xml:space="preserve">${xlsxEscape(s)}</t></si>`).join('\n')}
</sst>`;

  const sheetXmls = sheets.map((sheet) => {
    const rowsXml = sheet.rows
      .map((row, r) => {
        const cells = row.map((cell, c) => xlsxCell(c, r, cell, stringIndex.get(cell) ?? 0)).join('');
        return `<row r="${r + 1}">${cells}</row>`;
      })
      .join('');
    return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rowsXml}</sheetData></worksheet>`;
  });

  zip.file('[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>
  ${sheets.map((_, i) => `<Override PartName="/xl/worksheets/sheet${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('\n  ')}
</Types>`);

  zip.file('_rels/.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>`);

  zip.file('xl/_rels/workbook.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  ${sheets.map((_, i) => `<Relationship Id="rId${i + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i + 1}.xml"/>`).join('\n  ')}
  <Relationship Id="rIdShared" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>
</Relationships>`);

  zip.file('xl/workbook.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>
    ${sheets.map((s, i) => `<sheet name="${xlsxEscape(s.name)}" sheetId="${i + 1}" r:id="rId${i + 1}"/>`).join('\n    ')}
  </sheets>
</workbook>`);

  zip.file('xl/sharedStrings.xml', sharedStringsXml);
  sheetXmls.forEach((xml, i) => zip.file(`xl/worksheets/sheet${i + 1}.xml`, xml));

  return zip.generateAsync({
    type: 'blob',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
}

/* ------------------------------------------------------------------ */
/* PPTX (Office Open XML PresentationML)                               */
/* ------------------------------------------------------------------ */

interface SlideSpec {
  title: string;
  bullets: string[];
}

function buildSlidesForArtifact(artifact: Artifact): SlideSpec[] {
  const slides: SlideSpec[] = [];
  slides.push({
    title: artifact.name,
    bullets: buildHeaderRows(artifact).map(([k, v]) => `${k}: ${v}`),
  });
  if (artifact.executiveSummary) {
    slides.push({ title: 'Executive Summary', bullets: chunkParagraph(artifact.executiveSummary) });
  }
  ensureSections(artifact).forEach((section) => {
    slides.push({ title: section.title, bullets: chunkParagraph(section.content) });
  });
  return slides;
}

function chunkParagraph(text: string, maxBulletLen = 220): string[] {
  const lines = text.split(/\n+/).flatMap((l) => l.match(new RegExp(`.{1,${maxBulletLen}}(\\s|$)`, 'g')) ?? [l]);
  return lines.map((l) => l.trim()).filter(Boolean).slice(0, 8);
}

function pptxSlideXml(slide: SlideSpec): string {
  const titleRun = `<a:r><a:rPr lang="en-IN" b="1" sz="2800"/><a:t>${xmlEscape(slide.title)}</a:t></a:r>`;
  const bullets = slide.bullets
    .map(
      (b) => `<a:p><a:pPr lvl="0"/><a:r><a:rPr lang="en-IN" sz="1400"/><a:t>${xmlEscape(b)}</a:t></a:r></a:p>`,
    )
    .join('');
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
       xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
       xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name="grp"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="9144000" cy="6858000"/><a:chOff x="0" y="0"/><a:chExt cx="9144000" cy="6858000"/></a:xfrm></p:grpSpPr>

      <p:sp>
        <p:nvSpPr><p:cNvPr id="2" name="title"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr><p:ph type="ctrTitle"/></p:nvPr></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="457200" y="457200"/><a:ext cx="8229600" cy="800100"/></a:xfrm></p:spPr>
        <p:txBody><a:bodyPr/><a:lstStyle/><a:p>${titleRun}</a:p></p:txBody>
      </p:sp>

      <p:sp>
        <p:nvSpPr><p:cNvPr id="3" name="body"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr><p:ph idx="1"/></p:nvPr></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="457200" y="1371600"/><a:ext cx="8229600" cy="4800600"/></a:xfrm></p:spPr>
        <p:txBody><a:bodyPr/><a:lstStyle/>${bullets || '<a:p><a:r><a:rPr lang="en-IN" sz="1400"/><a:t> </a:t></a:r></a:p>'}</p:txBody>
      </p:sp>
    </p:spTree>
  </p:cSld>
</p:sld>`;
}

async function buildPptx(artifact: Artifact): Promise<Blob> {
  const zip = new JSZip();
  const slides = buildSlidesForArtifact(artifact);

  zip.file('[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  ${slides.map((_, i) => `<Override PartName="/ppt/slides/slide${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join('\n  ')}
</Types>`);

  zip.file('_rels/.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
</Relationships>`);

  zip.file('ppt/_rels/presentation.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  ${slides.map((_, i) => `<Relationship Id="rId${i + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${i + 1}.xml"/>`).join('\n  ')}
</Relationships>`);

  zip.file('ppt/presentation.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
                xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
                xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:sldIdLst>
    ${slides.map((_, i) => `<p:sldId id="${256 + i}" r:id="rId${i + 1}"/>`).join('\n    ')}
  </p:sldIdLst>
  <p:sldSz cx="9144000" cy="6858000" type="screen4x3"/>
  <p:notesSz cx="6858000" cy="9144000"/>
</p:presentation>`);

  slides.forEach((slide, i) => {
    zip.file(`ppt/slides/slide${i + 1}.xml`, pptxSlideXml(slide));
  });

  return zip.generateAsync({
    type: 'blob',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  });
}

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

function stripExtension(name: string): string {
  return name.replace(/\.(docx|xlsx|pptx|pdf|md|txt|yaml|yml|png)$/i, '');
}
