"""initial schema

Revision ID: 4ab6aec7d97a
Revises: 
Create Date: 2026-07-07 05:19:12.901759
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab6aec7d97a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('sponsor', sa.String(length=160), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['business_domains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_reference', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_project_id'), ['project_id'], unique=False)

    op.create_table('ai_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('likelihood', sa.String(length=20), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('exposure_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_risk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_risk_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_risk_reference'), ['reference'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('technology', sa.String(length=200), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['business_domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_name'), ['name'], unique=False)

    op.create_table('architecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('view_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('impacted_systems', sa.Text(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('architecture', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_architecture_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_architecture_reference'), ['reference'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('artifact_type', sa.String(length=40), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=120), nullable=False),
    sa.Column('model_used', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('preview_content', sa.Text(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('risk_rating', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_phase'), ['phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_reference'), ['reference'], unique=False)

    op.create_table('audit_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('evidence_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_evidence_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_evidence_reference'), ['reference'], unique=False)

    op.create_table('copilot_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('copilot_type', sa.String(length=40), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('badge', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('risk', sa.String(length=40), nullable=True),
    sa.Column('readiness', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copilot_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_findings_copilot_type'), ['copilot_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_copilot_findings_phase'), ['phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_copilot_findings_project_id'), ['project_id'], unique=False)

    op.create_table('executive_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=30), nullable=False),
    sa.Column('business_value', sa.Integer(), nullable=True),
    sa.Column('productivity_uplift_pct', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('ai_confidence', sa.Integer(), nullable=True),
    sa.Column('manual_effort_saved_days', sa.Integer(), nullable=True),
    sa.Column('documentation_pages', sa.Integer(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('requirements_score', sa.Integer(), nullable=True),
    sa.Column('architecture_score', sa.Integer(), nullable=True),
    sa.Column('development_score', sa.Integer(), nullable=True),
    sa.Column('testing_score', sa.Integer(), nullable=True),
    sa.Column('release_score', sa.Integer(), nullable=True),
    sa.Column('audit_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('executive_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executive_scores_project_id'), ['project_id'], unique=False)

    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('author', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_articles_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_articles_reference'), ['reference'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_project_id'), ['project_id'], unique=False)

    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deployment_plan', sa.Text(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('cab_summary', sa.Text(), nullable=True),
    sa.Column('monitoring_plan', sa.Text(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_releases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_releases_reference'), ['reference'], unique=False)

    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('requirement_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_reference'), ['reference'], unique=False)

    op.create_table('traceability_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.String(length=60), nullable=True),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_reference', sa.String(length=120), nullable=True),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_reference', sa.String(length=120), nullable=True),
    sa.Column('relationship_type', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traceability_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traceability_links_chain_id'), ['chain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traceability_links_project_id'), ['project_id'], unique=False)

    op.create_table('transformation_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('benefit_value', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transformation_programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transformation_programs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transformation_programs_reference'), ['reference'], unique=False)

    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('copilot_type', sa.String(length=40), nullable=True),
    sa.Column('badge', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('impact', sa.String(length=300), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['copilot_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_recommendations_copilot_type'), ['copilot_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_project_id'), ['project_id'], unique=False)

    op.create_table('architecture_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('architecture_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['architecture_id'], ['architecture.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('architecture_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_architecture_review_architecture_id'), ['architecture_id'], unique=False)

    op.create_table('audit_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['audit_evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_observations_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('compliance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('framework', sa.String(length=80), nullable=False),
    sa.Column('control_reference', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['audit_evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_records_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=60), nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deployed_by', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_release_id'), ['release_id'], unique=False)

    op.create_table('development_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('assignee', sa.String(length=160), nullable=True),
    sa.Column('feature_flag', sa.String(length=120), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('development_stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_development_stories_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_development_stories_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_development_stories_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('go_live',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=30), nullable=False),
    sa.Column('checklist', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=160), nullable=True),
    sa.Column('go_live_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('go_live', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_go_live_release_id'), ['release_id'], unique=False)

    op.create_table('requirement_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('gap', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_analysis_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('test_type', sa.String(length=30), nullable=False),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_cases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('code_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('is_secure_coding', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['development_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_review_story_id'), ['story_id'], unique=False)

    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defects_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('development_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('estimate_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['development_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('development_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_development_tasks_story_id'), ['story_id'], unique=False)

    op.create_table('source_code_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('repository', sa.String(length=200), nullable=False),
    sa.Column('module', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=60), nullable=True),
    sa.Column('lines_of_code', sa.Integer(), nullable=True),
    sa.Column('complexity', sa.Integer(), nullable=True),
    sa.Column('coverage_pct', sa.Integer(), nullable=True),
    sa.Column('code_smells', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['development_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_code_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_code_metadata_story_id'), ['story_id'], unique=False)

    op.create_table('test_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('executed_by', sa.String(length=160), nullable=True),
    sa.Column('environment', sa.String(length=60), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_execution_test_case_id'), ['test_case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_execution_test_case_id'))

    op.drop_table('test_execution')
    with op.batch_alter_table('source_code_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_code_metadata_story_id'))

    op.drop_table('source_code_metadata')
    with op.batch_alter_table('development_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_development_tasks_story_id'))

    op.drop_table('development_tasks')
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defects_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_defects_reference'))
        batch_op.drop_index(batch_op.f('ix_defects_project_id'))

    op.drop_table('defects')
    with op.batch_alter_table('code_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_review_story_id'))

    op.drop_table('code_review')
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_test_cases_reference'))
        batch_op.drop_index(batch_op.f('ix_test_cases_project_id'))

    op.drop_table('test_cases')
    with op.batch_alter_table('requirement_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_analysis_requirement_id'))

    op.drop_table('requirement_analysis')
    with op.batch_alter_table('go_live', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_go_live_release_id'))

    op.drop_table('go_live')
    with op.batch_alter_table('development_stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_development_stories_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_development_stories_reference'))
        batch_op.drop_index(batch_op.f('ix_development_stories_project_id'))

    op.drop_table('development_stories')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_release_id'))

    op.drop_table('deployments')
    with op.batch_alter_table('compliance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_records_evidence_id'))

    op.drop_table('compliance_records')
    with op.batch_alter_table('audit_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_observations_evidence_id'))

    op.drop_table('audit_observations')
    with op.batch_alter_table('architecture_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_architecture_review_architecture_id'))

    op.drop_table('architecture_review')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_project_id'))
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_finding_id'))
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_copilot_type'))

    op.drop_table('ai_recommendations')
    with op.batch_alter_table('transformation_programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transformation_programs_reference'))
        batch_op.drop_index(batch_op.f('ix_transformation_programs_project_id'))

    op.drop_table('transformation_programs')
    with op.batch_alter_table('traceability_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traceability_links_project_id'))
        batch_op.drop_index(batch_op.f('ix_traceability_links_chain_id'))

    op.drop_table('traceability_links')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_reference'))
        batch_op.drop_index(batch_op.f('ix_requirements_project_id'))

    op.drop_table('requirements')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_reference'))
        batch_op.drop_index(batch_op.f('ix_releases_project_id'))

    op.drop_table('releases')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_project_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('knowledge_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_articles_reference'))
        batch_op.drop_index(batch_op.f('ix_knowledge_articles_project_id'))

    op.drop_table('knowledge_articles')
    with op.batch_alter_table('executive_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executive_scores_project_id'))

    op.drop_table('executive_scores')
    with op.batch_alter_table('copilot_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_findings_project_id'))
        batch_op.drop_index(batch_op.f('ix_copilot_findings_phase'))
        batch_op.drop_index(batch_op.f('ix_copilot_findings_copilot_type'))

    op.drop_table('copilot_findings')
    with op.batch_alter_table('audit_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_evidence_reference'))
        batch_op.drop_index(batch_op.f('ix_audit_evidence_project_id'))

    op.drop_table('audit_evidence')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_reference'))
        batch_op.drop_index(batch_op.f('ix_artifacts_project_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_phase'))
        batch_op.drop_index(batch_op.f('ix_artifacts_artifact_type'))

    op.drop_table('artifacts')
    with op.batch_alter_table('architecture', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_architecture_reference'))
        batch_op.drop_index(batch_op.f('ix_architecture_project_id'))

    op.drop_table('architecture')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_name'))

    op.drop_table('applications')
    with op.batch_alter_table('ai_risk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_risk_reference'))
        batch_op.drop_index(batch_op.f('ix_ai_risk_project_id'))

    op.drop_table('ai_risk')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_project_id'))

    op.drop_table('activity_log')
    op.drop_table('user_roles')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('business_domains')
    # ### end Alembic commands ###
