"""prompt studio fields

Revision ID: ec97df09e28f
Revises: f007eb90a303
Create Date: 2026-07-08 05:44:43.735265
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec97df09e28f'
down_revision: Union[str, None] = 'f007eb90a303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workbench_prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('approval_status', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workbench_prompts', schema=None) as batch_op:
        batch_op.drop_column('is_published')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('is_favorite')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
